// 共通UIと地図描画をAviUtl2へ公開するDLL入口。
library SYNC_MapRaku_Filter;
{$ALIGN 8}
uses
  AviUtl2FilterTypes in 'Lib\AviUtl2\AviUtl2FilterTypes.pas',
  PluginFilterTable in 'Lib\AviUtl2\PluginFilterTable.pas',
  PluginFilterContextManager in 'Lib\AviUtl2\PluginFilterContextManager.pas',
  MapRakuFilterPlugin in 'Source\PlacementPlugin\MapRakuFilterPlugin.pas',
  MapRakuFilterContext in 'Source\PlacementPlugin\MapRakuFilterContext.pas',
  MapRakuPluginDocument in 'Source\PlacementPlugin\MapRakuPluginDocument.pas',
  MapRakuEditorHost in 'Source\PlacementPlugin\MapRakuEditorHost.pas',
  MapRakuFrameCapture in 'Source\PlacementPlugin\MapRakuFrameCapture.pas',
  Vcl.Forms,
  MapRakuRenderBuffer in 'Source\Rendering\Buffer\MapRakuRenderBuffer.pas',
  MapRakuPathEditSession in 'Source\Core\Commands\Path\MapRakuPathEditSession.pas',
  MapRakuCrossingGeometry in 'Source\Map\Crossings\MapRakuCrossingGeometry.pas',
  MapRakuBridgeSpans in 'Source\Map\Crossings\MapRakuBridgeSpans.pas',
  MapRakuCrossingRenderer in 'Source\Map\Rendering\Crossings\MapRakuCrossingRenderer.pas',
  MapRakuPathEditor in 'Source\Map\Editing\MapRakuPathEditor.pas',
  MapRakuFile in 'Source\Map\Export\MapRakuFile.pas',
  MapRakuPathSnap in 'Source\Map\Editing\MapRakuPathSnap.pas',
  MapRakuTheme in 'Source\Map\Appearance\MapRakuTheme.pas',
  MapRakuSymbolsk in 'Source\Map\Symbols\MapRakuSymbols.pas',
  MapRakuExport in 'Source\Map\Export\MapRakuExport.pas',
  MapRakuMapCommands in 'Source\Map\Commands\MapRakuMapCommands.pas',
  MapRakuCrossings in 'Source\Map\Crossings\MapRakuCrossings.pas',
  MapRakuMapPanel in 'Source\Map\UI\MapRakuMapPanel.pas',
  MapRakuPathRenderer in 'Source\Map\Rendering\Paths\MapRakuPathRenderer.pas',
  MapRakuRailRenderer in 'Source\Map\Rendering\Paths\MapRakuRailRenderer.pas',
  MapRakuRiverRenderer in 'Source\Map\Rendering\Paths\MapRakuRiverRenderer.pas',
  MapRakuRoadRenderer in 'Source\Map\Rendering\Paths\MapRakuRoadRenderer.pas',
  MapRakuStairRenderer in 'Source\Map\Rendering\Paths\MapRakuStairRenderer.pas',
  TextRendererSkiaBootstrap in 'Lib\TextRenderer\TextRendererSkiaBootstrap.pas',
  TextRendererTypes in 'Lib\TextRenderer\TextRendererTypes.pas',
  TextRenderer in 'Lib\TextRenderer\TextRenderer.pas',
  TextRendererSkiaRuntime in 'Lib\TextRenderer\TextRendererSkiaRuntime.pas',
  TextRendererSkia in 'Lib\TextRenderer\TextRendererSkia.pas',
  VectArtDarkPopupMenu in 'Lib\DarkMenu\VectArtDarkPopupMenu.pas',
  VectArtDarkMenuGroup in 'Lib\DarkMenu\VectArtDarkMenuGroup.pas',
  ShortcutAction in 'Lib\ShortcutAction\ShortcutAction.pas',
  HorizontalTrackBarRenderer in 'Lib\HorizontalTrackBar\HorizontalTrackBarRenderer.pas',
  HorizontalTrackBarControl in 'Lib\HorizontalTrackBar\HorizontalTrackBarControl.pas',
  PipeServerTThread in 'Lib\Pipe\PipeServerTThread.pas',
  MapRakuAutomationBatch in 'Source\Automation\Map\MapRakuAutomationBatch.pas',
  MapRakuAutomationFactory in 'Source\Automation\Map\MapRakuAutomationFactory.pas',
  MapRakuAutomationSchema in 'Source\Automation\Map\MapRakuAutomationSchema.pas',
  MapRakuAutomationValidation in 'Source\Automation\Map\MapRakuAutomationValidation.pas',
  MapRakuAutomationValues in 'Source\Automation\Map\MapRakuAutomationValues.pas',
  MapRakuAutomationBlobs in 'Source\Automation\Transport\MapRakuAutomationBlobs.pas',
  MapRakuAutomationReference in 'Source\Automation\Transport\MapRakuAutomationReference.pas',
  MapRakuAutomationSession in 'Source\Automation\Transport\MapRakuAutomationSession.pas',
  MapRakuAutomationWire in 'Source\Automation\MapRakuAutomationWire.pas',
  MapRakuAutomationServices in 'Source\Automation\MapRakuAutomationServices.pas',
  MapRakuAutomationVisuals in 'Source\Automation\MapRakuAutomationVisuals.pas',
  MapRakuAutomationText in 'Source\Automation\MapRakuAutomationText.pas',
  MapRakuAutomationLayout in 'Source\Automation\MapRakuAutomationLayout.pas',
  MapRakuAutomationProtocol in 'Source\Automation\MapRakuAutomationProtocol.pas',
  MapRakuAutomationPipeServer in 'Source\Automation\MapRakuAutomationPipeServer.pas',
  MapRakuAutomationDocumentCommand in 'Source\Automation\MapRakuAutomationDocumentCommand.pas',
  MapRakuPlacementPreview in 'Source\Editor\Creation\MapRakuPlacementPreview.pas',
  MapRakuColorHistory in 'Source\ObjectProperties\Color\MapRakuColorHistory.pas',
  MapRakuColorCode in 'Source\ObjectProperties\Color\MapRakuColorCode.pas',
  MapRakuMainForm in 'Source\Shell\MapRakuMainForm.pas' {MainForm},
  MapRakuObjectContextMenu in 'Source\Shell\Menus\MapRakuObjectContextMenu.pas',
  MapRakuTextContextMenu in 'Source\Shell\Menus\MapRakuTextContextMenu.pas',
  MapRakuPathContextMenu in 'Source\Shell\Menus\MapRakuPathContextMenu.pas',
  MapRakuTransformContextMenu in 'Source\Shell\Menus\MapRakuTransformContextMenu.pas',
  MapRakuArrangementContextMenu in 'Source\Shell\Menus\MapRakuArrangementContextMenu.pas',
  MapRakuEditActionsUI in 'Source\Shell\Toolbars\MapRakuEditActionsUI.pas',
  MapRakuStrokeStyleCombo in 'Source\ObjectProperties\Geometry\MapRakuStrokeStyleCombo.pas',
  MapRakuLineToolbar in 'Source\Shell\Toolbars\MapRakuLineToolbar.pas',
  MapRakuLineToolbarOperations in 'Source\Shell\Toolbars\MapRakuLineToolbarOperations.pas',
  MapRakuTextToolbarOperations in 'Source\Shell\Toolbars\MapRakuTextToolbarOperations.pas',
  MapRakuLineStyleControls in 'Source\Shell\Toolbars\MapRakuLineStyleControls.pas',
  MapRakuCanvasSettingsDialog in 'Source\Shell\MapRakuCanvasSettingsDialog.pas',
  MapRakuCanvasColorDialog in 'Source\Shell\MapRakuCanvasColorDialog.pas',
  MapRakuDarkDialogControls in 'Source\Shell\MapRakuDarkDialogControls.pas',
  MapRakuProjectiveTransform in 'Source\Core\Geometry\MapRakuProjectiveTransform.pas',
  MapRakuTransformInteraction in 'Source\Editor\Interaction\Transform\MapRakuTransformInteraction.pas',
  MapRakuDocument in 'Source\Core\Model\MapRakuDocument.pas',
  MapRakuPaintStyles in 'Source\Core\Model\MapRakuPaintStyles.pas',
  MapRakuTextureInteraction in 'Source\Editor\Interaction\Texture\MapRakuTextureInteraction.pas',
  MapRakuTextureStyle in 'Source\Core\Model\MapRakuTextureStyle.pas',
  MapRakuPatternStyle in 'Source\Core\Model\Pattern\MapRakuPatternStyle.pas',
  MapRakuPatternRenderer in 'Source\Rendering\Paint\Pattern\MapRakuPatternRenderer.pas',
  MapRakuPatternJson in 'Source\Persistence\MapRakuPatternJson.pas',
  MapRakuPatternControl in 'Source\ObjectProperties\Color\Pattern\MapRakuPatternControl.pas',
  MapRakuPatternControlRenderer in 'Source\ObjectProperties\Color\Pattern\MapRakuPatternControlRenderer.pas',
  MapRakuPaintStyleGesture in 'Source\ObjectProperties\Color\Pattern\MapRakuPaintStyleGesture.pas',
  MapRakuTextureRenderer in 'Source\Rendering\Paint\MapRakuTextureRenderer.pas',
  MapRakuTextureJson in 'Source\Persistence\MapRakuTextureJson.pas',
  MapRakuTextureControl in 'Source\ObjectProperties\Color\Texture\MapRakuTextureControl.pas',
  MapRakuPaintModeSelector in 'Source\ObjectProperties\Color\MapRakuPaintModeSelector.pas',
  MapRakuColorTargetSelector in 'Source\ObjectProperties\Color\MapRakuColorTargetSelector.pas',
  MapRakuTextureDropTarget in 'Source\ObjectProperties\Color\Texture\MapRakuTextureDropTarget.pas',
  MapRakuTextDecompositionCommands in 'Source\Core\Commands\Text\MapRakuTextDecompositionCommands.pas',
  MapRakuFilters in 'Source\Core\Model\MapRakuFilters.pas',
  MapRakuGeometry in 'Source\Core\Geometry\MapRakuGeometry.pas',
  MapRakuEllipseGeometry in 'Source\Core\Geometry\Shape\MapRakuEllipseGeometry.pas',
  MapRakuTextGeometry in 'Source\Core\Geometry\Text\MapRakuTextGeometry.pas',
  MapRakuTextPathGeometry in 'Source\Core\Geometry\Text\MapRakuTextPathGeometry.pas',
  MapRakuTextOutlineGeometry in 'Source\Core\Geometry\Text\MapRakuTextOutlineGeometry.pas',
  MapRakuPathOperations in 'Source\Core\Geometry\Shape\MapRakuPathOperations.pas',
  MapRakuShapeOperations in 'Source\Core\Geometry\Shape\MapRakuShapeOperations.pas',
  MapRakuShapeBooleanGeometry in 'Source\Core\Geometry\Shape\MapRakuShapeBooleanGeometry.pas',
  MapRakuStrokeOutlineGeometry in 'Source\Core\Geometry\Shape\MapRakuStrokeOutlineGeometry.pas',
  MapRakuShapeBooleanOperations in 'Source\Core\Geometry\Shape\MapRakuShapeBooleanOperations.pas',
  MapRakuLayerGeometry in 'Source\Core\Geometry\MapRakuLayerGeometry.pas',
  MapRakuRenderer in 'Source\Rendering\MapRakuRenderer.pas',
  MapRakuCanvasRenderCache in 'Source\Rendering\Cache\MapRakuCanvasRenderCache.pas',
  MapRakuPaintRenderer in 'Source\Rendering\Paint\MapRakuPaintRenderer.pas',
  MapRakuVariableWidthRenderer in 'Source\Rendering\Paint\MapRakuVariableWidthRenderer.pas',
  MapRakuStrokeSampling in 'Source\Rendering\Paint\Stroke\MapRakuStrokeSampling.pas',
  MapRakuCanvasGuides in 'Source\Rendering\MapRakuCanvasGuides.pas',
  MapRakuCanvasPreview in 'Source\Rendering\MapRakuCanvasPreview.pas',
  MapRakuOverlayPrimitives in 'Source\Rendering\Overlay\MapRakuOverlayPrimitives.pas',
  MapRakuOverlayShapes in 'Source\Rendering\Overlay\MapRakuOverlayShapes.pas',
  MapRakuOverlayHandles in 'Source\Rendering\Overlay\MapRakuOverlayHandles.pas',
  MapRakuGradientOverlay in 'Source\Rendering\Overlay\MapRakuGradientOverlay.pas',
  MapRakuTextEditOverlay in 'Source\Rendering\MapRakuTextEditOverlay.pas',
  MapRakuShapePath in 'Source\Rendering\MapRakuShapePath.pas',
  MapRakuContext in 'Source\Core\Model\MapRakuContext.pas',
  MapRakuEditorState in 'Source\Core\Model\MapRakuEditorState.pas',
  MapRakuEditCommands in 'Source\Core\Commands\MapRakuEditCommands.pas',
  MapRakuShapeEditCommands in 'Source\Core\Commands\Shape\MapRakuShapeEditCommands.pas',
  MapRakuShapeBooleanCommands in 'Source\Core\Commands\Shape\MapRakuShapeBooleanCommands.pas',
  MapRakuStrokeOutlineCommands in 'Source\Core\Commands\Shape\MapRakuStrokeOutlineCommands.pas',
  MapRakuTextCommands in 'Source\Core\Commands\Text\MapRakuTextCommands.pas',
  MapRakuLayerStructureCommands in 'Source\Core\Commands\Layer\MapRakuLayerStructureCommands.pas',
  MapRakuLayerBatchCommands in 'Source\Core\Commands\Layer\MapRakuLayerBatchCommands.pas',
  MapRakuGroupCommands in 'Source\Core\Commands\Layer\Group\MapRakuGroupCommands.pas',
  MapRakuGroupChildCommands in 'Source\Core\Commands\Layer\Group\MapRakuGroupChildCommands.pas',
  MapRakuGroupTransformCommands in 'Source\Core\Commands\Layer\Group\MapRakuGroupTransformCommands.pas',
  MapRakuLayerFlipOperations in 'Source\Core\Commands\Layer\Transform\MapRakuLayerFlipOperations.pas',
  MapRakuLayerArrangementOperations in 'Source\Core\Commands\Layer\Transform\MapRakuLayerArrangementOperations.pas',
  MapRakuLayerTransformCommands in 'Source\Core\Commands\Layer\Transform\MapRakuLayerTransformCommands.pas',
  MapRakuFilterCommands in 'Source\Core\Commands\MapRakuFilterCommands.pas',
  MapRakuPaintCommands in 'Source\Core\Commands\MapRakuPaintCommands.pas',
  MapRakuEditHistory in 'Source\Core\Model\MapRakuEditHistory.pas',
  MapRakuDocumentJson in 'Source\Persistence\MapRakuDocumentJson.pas',
  MapRakuDocumentJsonReader in 'Source\Persistence\MapRakuDocumentJsonReader.pas',
  MapRakuDocumentJsonWriter in 'Source\Persistence\MapRakuDocumentJsonWriter.pas',
  MapRakuCanvas in 'Source\Editor\MapRakuCanvas.pas',
  MapRakuCanvasInteraction in 'Source\Editor\Interaction\MapRakuCanvasInteraction.pas',
  MapRakuSnapGeometry in 'Source\Core\Geometry\MapRakuSnapGeometry.pas',
  MapRakuTextPathCharacterInteraction in
    'Source\Editor\Interaction\Text\MapRakuTextPathCharacterInteraction.pas',
  MapRakuContextMenuInteraction in 'Source\Editor\Interaction\MapRakuContextMenuInteraction.pas',
  MapRakuFilterInteraction in 'Source\Editor\Interaction\Filter\MapRakuFilterInteraction.pas',
  MapRakuGradientInteraction in 'Source\Editor\Interaction\Gradient\MapRakuGradientInteraction.pas',
  MapRakuGroupInteraction in 'Source\Editor\Interaction\Group\MapRakuGroupInteraction.pas',
  MapRakuTextEditing in 'Source\Editor\Interaction\Text\MapRakuTextEditing.pas',
  MapRakuInteractionGeometry in 'Source\Editor\Interaction\MapRakuInteractionGeometry.pas',
  MapRakuPathInteraction in 'Source\Editor\Interaction\Shape\MapRakuPathInteraction.pas',
  MapRakuShapeInteraction in 'Source\Editor\Interaction\Shape\MapRakuShapeInteraction.pas',
  MapRakuShapeCreation in 'Source\Editor\Creation\MapRakuShapeCreation.pas',
  MapRakuLayerNaming in 'Source\Editor\Creation\MapRakuLayerNaming.pas',
  MapRakuImageImport in 'Source\Editor\Creation\MapRakuImageImport.pas',
  MapRakuKeyboardMovement in 'Source\Editor\Interaction\MapRakuKeyboardMovement.pas',
  MapRakuEditorWorkspaceFrame in 'Source\Editor\MapRakuEditorWorkspaceFrame.pas',
  MapRakuSelectionGeometry in 'Source\Editor\Interaction\MapRakuSelectionGeometry.pas',
  MapRakuLayerList in 'Source\Layers\List\MapRakuLayerList.pas',
  MapRakuLayerItemPainter in 'Source\Layers\List\MapRakuLayerItemPainter.pas',
  MapRakuLayerListStyle in 'Source\Layers\List\MapRakuLayerListStyle.pas',
  MapRakuLayerSelection in 'Source\Layers\List\MapRakuLayerSelection.pas',
  MapRakuLayerThumbnailCache in 'Source\Layers\List\MapRakuLayerThumbnailCache.pas',
  MapRakuObjectClipboard in 'Source\Layers\Clipboard\MapRakuObjectClipboard.pas',
  MapRakuInsertObjectsCommand in 'Source\Core\Commands\Layer\MapRakuInsertObjectsCommand.pas',
  MapRakuDeleteLayersCommand in 'Source\Core\Commands\Layer\MapRakuDeleteLayersCommand.pas',
  MapRakuLayerRenderer in 'Source\Layers\List\MapRakuLayerRenderer.pas',
  MapRakuLayerActions in 'Source\Layers\Operations\MapRakuLayerActions.pas',
  MapRakuLayerOperations in 'Source\Layers\Operations\MapRakuLayerOperations.pas',
  MapRakuLayerDuplication in 'Source\Layers\Operations\MapRakuLayerDuplication.pas',
  MapRakuLayerPanelFrame in 'Source\Layers\MapRakuLayerPanelFrame.pas',
  MapRakuDockManager in 'Source\Layout\MapRakuDockManager.pas',
  MapRakuToolFrames in 'Source\Layout\MapRakuToolFrames.pas',
  MapRakuObjectPropertiesControl in 'Source\ObjectProperties\MapRakuObjectPropertiesControl.pas',
  MapRakuFilterDetailsFrame in 'Source\ObjectProperties\Filters\MapRakuFilterDetailsFrame.pas',
  MapRakuFilterListControl in 'Source\ObjectProperties\Filters\MapRakuFilterListControl.pas',
  MapRakuFilterFrame in 'Source\ObjectProperties\Filters\MapRakuFilterFrame.pas',
  MapRakuObjectPropertiesFrame in 'Source\ObjectProperties\MapRakuObjectPropertiesFrame.pas',
  MapRakuToolPaletteFrame in 'Source\ToolPalette\MapRakuToolPaletteFrame.pas',
  MapRakuToolPalette in 'Source\ToolPalette\MapRakuToolPalette.pas',
  WindowsImeController in 'Lib\InputMethod\WindowsImeController.pas';

function InitializePlugin(Version: Cardinal): Byte; cdecl;
begin
  // ホスト境界では初期化失敗を戻り値で通知する。
  try
    InitializeMapRakuFilter;
    Result := 1;
  except
    // 初期化側が途中まで取得した描画資源を巻き戻す。
    Result := 0;
  end;
end;

procedure UninitializePlugin; cdecl;
begin
  try
    FinalizeMapRakuFilter;
  except
    // ホストの終了処理をDelphi例外で中断しない。
  end;
end;

function GetFilterPluginTable: PFILTER_PLUGIN_TABLE; cdecl;
begin
  try
    Result := GetMapRakuFilterTable;
  except
    Result := nil;
  end;
end;

exports
  InitializePlugin name 'InitializePlugin',
  UninitializePlugin name 'UninitializePlugin',
  GetFilterPluginTable name 'GetFilterPluginTable';

begin
end.
